packages:
  - 'packages/*'
  - 'playground'
  - 'benchmarks'
  - 'benchmarks/runner'
  - 'benchmarks/runner/app'
  - 'benchmarks/frameworks/*'
allowBuilds:
  '@vscode/vsce-sign': true
  keytar: true
  esbuild: true
  '@parcel/watcher': true
  lmdb: true
  msgpackr-extract: true
overrides:
  typescript: '^6.0.3'
